import {
  ShoppingCart,
  Car,
  Home,
  UtensilsCrossed,
  Ticket,
  ConciergeBell,
  Shirt,
  HeartPulse,
  Tag,
} from 'lucide-react';
import type { Transaction, Category } from './types';

export const INITIAL_CATEGORIES: Category[] = [
  { value: 'groceries', label: 'Groceries', icon: ShoppingCart },
  { value: 'food', label: 'Food', icon: UtensilsCrossed },
  { value: 'transportation', label: 'Transportation', icon: Car },
  { value: 'housing', label: 'Housing', icon: Home },
  { value: 'entertainment', label: 'Entertainment', icon: Ticket },
  { value: 'services', label: 'Services', icon: ConciergeBell },
  { value: 'clothing', label: 'Clothing', icon: Shirt },
  { value: 'health', label: 'Health', icon: HeartPulse },
  { value: 'other', label: 'Other', icon: Tag },
];

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: '1',
    date: '01/08/25',
    narration: 'UPI-SWIGGY LIMITED-SWIGGY1ONLINE.GPAY@OKPAYAXIS',
    amount: 450.0,
    type: 'withdrawal',
    closingBalance: 177254.76,
    category: '',
    status: 'unprocessed',
  },
  {
    id: '2',
    date: '03/08/25',
    narration: 'UPI-NELLAI MUTTON SHOP-NELLAIMUTTON@TMB-CHICKEN',
    amount: 520.0,
    type: 'withdrawal',
    closingBalance: 176734.76,
    category: '',
    status: 'unprocessed',
  },
  {
    id: '3',
    date: '03/08/25',
    narration: 'UPI-MOSES RAJ R-Q873294065@YBL-GROSEERY',
    amount: 160.0,
    type: 'withdrawal',
    closingBalance: 176574.76,
    category: '',
    status: 'unprocessed',
  },
  {
    id: '4',
    date: '03/08/25',
    narration: 'UPI-LOGANATHAN R-9677296548@OKBIZAXIS-VEGIS',
    amount: 119.0,
    type: 'withdrawal',
    closingBalance: 176455.76,
    category: '',
    status: 'unprocessed',
  },
  {
    id: '5',
    date: '03/08/25',
    narration: 'UPI-REDBUS-REDBUS1.DBQR.PAYU@INDUS-UPI',
    amount: 4039.89,
    type: 'withdrawal',
    closingBalance: 172415.87,
    category: '',
    status: 'unprocessed',
  },
  {
    id: '6',
    date: '03/08/25',
    narration: 'UPI-JEYACHANDRAN PALLIKA-PAYMENT FOR PINE61',
    amount: 2999.0,
    type: 'withdrawal',
    closingBalance: 169416.87,
    category: '',
    status: 'unprocessed',
  },
];
